'use client';
import {useState,useEffect} from 'react';
import {CalendarDays,ArrowUpRight,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api} from '@/lib/client';
export default function Home(){
 const [names,setNames]=useState(['','Minhao','','','']),[title,setTitle]=useState('Monthly supervision meeting'),[timezone,setTimezone]=useState('Europe/London'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[existing,setExisting]=useState('');
 useEffect(()=>setExisting(localStorage.getItem('circle-management-link')||''),[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{id:string;admin:string}>('/api/circles','POST',{names,title,timezone});const url='/circle/'+result.id+'#admin='+result.admin;localStorage.setItem('circle-management-link',location.origin+url);location.assign(url);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="site-shell"><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><CalendarDays size={22}/></span>Supervision Circle</a>{existing?<a className="text-link" href={existing}>Open your circle <ArrowUpRight size={16}/></a>:<span className="topnote">A little less back-and-forth.</span>}</header><main className="setup-layout"><section className="intro"><p className="eyebrow">YOUR MONTHLY MEETING, TOGETHER</p><h1>Five people.<br/>One good time.</h1><p className="lede">Bring everyone’s availability into one place. Find a time that works, then make it official in Outlook.</p><div className="meeting-facts"><span><Users size={18}/>5 people</span><span><CalendarDays size={18}/>45 minutes · monthly</span></div><div className="steps"><p><b>01</b> Propose a few times</p><p><b>02</b> Share one link with everyone</p><p><b>03</b> Choose together, confirm in Outlook</p></div></section><section className="panel setup-panel"><p className="eyebrow">START YOUR CIRCLE</p><h2>Who’s at the table?</h2><p className="muted">You and your four supervisors. You can edit these names later.</p><form onSubmit={create}><label>Meeting name<Input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100}/></label><div className="name-fields">{names.map((name,i)=><label key={i}>{i===0?'Your name · organiser':'Supervisor '+i}<Input value={name} onChange={e=>setNames(names.map((n,j)=>i===j?e.target.value:n))} placeholder={i===0?'Your name':'Full name'} required maxLength={60}/></label>)}</div><label>Meeting time zone<Input value={timezone} onChange={e=>setTimezone(e.target.value)} required/></label>{error&&<p className="field-error" role="alert">{error}</p>}<Button className="primary-button" type="submit" disabled={busy}>{busy?'Creating…':'Create your circle'}<ArrowUpRight size={17}/></Button></form><p className="fine">One shared link. No accounts needed for your supervisors.</p></section></main><footer>Made for the conversation that matters.</footer></div>;
}
