'use client';
import {useState,useEffect,useCallback,useMemo,useRef} from 'react';
import {CalendarDays,Users,Clock,ArrowUpRight,Plus,Copy,Check,Star,HelpCircle,X,Trash2,Settings,RefreshCw,ExternalLink,ArrowLeft,Link2,Send,LockKeyhole} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyContent} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {api,shareKey} from '@/lib/client';
import {RESPONSES,LABELS,ranked,summary,localParts,monthLabel,formatSlot,type Choice,type Snapshot,type Poll,type Slot,type Circle} from '@/lib/domain';

const icons={best:Star,available:Check,check:HelpCircle,unavailable:X};
type Change={value:Choice|null;before:Choice|null};
type Drafts=Record<string,Record<string,Change>>;
function initials(name:string){return name.split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();}
function dateLabel(iso:string,zone:string){return new Intl.DateTimeFormat('en-GB',{timeZone:zone,day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));}
function nextMonth(zone:string){const now=localParts(new Date().toISOString(),zone);const date=new Date(now.date+'T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+1,1);return date.toISOString().slice(0,7);}
function defaultDeadline(zone:string){const date=new Date();for(let i=0;i<3;){date.setUTCDate(date.getUTCDate()+1);if(![0,6].includes(date.getUTCDay()))i++;}return localParts(date.toISOString(),zone).date+'T17:00';}
function Status({value}:{value?:Choice}){if(!value)return <span className="vote-status none"><span className="empty-dot"/>No response</span>;const Icon=icons[value];return <span className={'vote-status '+value}><Icon size={14}/>{LABELS[value]}</span>;}
function MemberPicker({circle,value,onChange,disabled=false}:{circle:Circle;value:string;onChange:(id:string)=>void;disabled?:boolean}){return <Select value={value||null} onValueChange={v=>onChange(String(v??''))} disabled={disabled}><SelectTrigger aria-label="Choose your name" className="picker"><SelectValue placeholder="Choose your name">{circle.members.find(m=>m.id===value)?.name}</SelectValue></SelectTrigger><SelectContent>{circle.members.map(m=><SelectItem key={m.id} value={m.id}>{m.name}{m.id===circle.organiserId?' · organiser':''}</SelectItem>)}</SelectContent></Select>;}

export default function MeetingApp({id}:{id:string}){
 const [token,setToken]=useState(''),[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [memberId,setMemberId]=useState(''),[pollId,setPollId]=useState(''),[mode,setMode]=useState('availability'),[drafts,setDrafts]=useState<Drafts>({});
 const [shared,setShared]=useState(''),[manageUrl,setManageUrl]=useState(''),[settings,setSettings]=useState(false),[createOpen,setCreateOpen]=useState(false);
 const [textModal,setTextModal]=useState<{title:string;text:string}|null>(null),[remove,setRemove]=useState<Slot|null>(null),[decision,setDecision]=useState<{slot:Slot;revision:number}|null>(null),[reopen,setReopen]=useState(false),[discard,setDiscard]=useState(false);
 const absorb=useCallback((value:Snapshot)=>setData(old=>!old||value.revision>=old.revision?value:old),[]);
 useEffect(()=>{
  const hash=new URLSearchParams(location.hash.slice(1));const provided=hash.get('admin')||hash.get('key');const stored=sessionStorage.getItem('circle-key:'+id);const key=provided||stored||'';
  if(!key){setError('Open this page using the shared link or your management link.');return;}
  sessionStorage.setItem('circle-key:'+id,key);setToken(key);setMemberId(localStorage.getItem('circle-member:'+id)||'');
 },[id]);
 const refresh=useCallback(async()=>{if(!token)return;const latest=await api<Snapshot>('/api/circles/'+id,'GET',undefined,token);absorb(latest);return latest;},[id,token,absorb]);
 useEffect(()=>{if(!token)return;let active=true;refresh().then(value=>{if(!active||!value)return;if(value.role==='admin'){setMode('manage');setMemberId(old=>old||value.circle.organiserId);const url=location.origin+location.pathname+'#admin='+token;setManageUrl(url);localStorage.setItem('circle-management-link',url);shareKey(token).then(k=>active&&setShared(location.origin+location.pathname+'#key='+k));}else setShared(location.origin+location.pathname+'#key='+token);}).catch(e=>setError(e.message));
 const tick=()=>{if(document.visibilityState==='visible')refresh().catch(()=>{});};const timer=setInterval(tick,15000);window.addEventListener('focus',tick);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',tick);};},[token,id,refresh]);
 const polls=useMemo(()=>data?[...data.circle.polls].sort((a,b)=>b.month.localeCompare(a.month)):[],[data]);
 const poll=polls.find(p=>p.id===pollId)||polls[0];const circle=data?.circle;const admin=data?.role==='admin';
 const draftKey= (poll?.id??'')+':'+memberId;const changes=drafts[draftKey]||{};const dirty=Object.keys(changes).length;
 const currentMember=circle?.members.find(m=>m.id===memberId);
 const candidates=useMemo(()=>circle&&poll?ranked(poll,circle):[],[circle,poll]);
 const unlocked=!!poll&&(poll.status==='open'||(admin&&poll.status==='draft'));
 const info=(message:string)=>{setNotice(message);setError('');};
 async function operation(op:unknown){setBusy(true);setError('');try{const result=await api<Snapshot>('/api/circles/'+id,'PATCH',op,token);absorb(result);return result;}catch(e){const message=e instanceof Error?e.message:'Please try again.';setError(message);await refresh().catch(()=>{});throw e;}finally{setBusy(false);}}
 function selectMember(value:string){setMemberId(value);localStorage.setItem('circle-member:'+id,value);}
 function changeVote(slot:Slot,value:Choice|null){setNotice('');setDrafts(old=>{const current={...(old[draftKey]||{})},baseline=current[slot.id]?current[slot.id].before:(slot.votes[memberId]??null);if(value===baseline)delete current[slot.id];else current[slot.id]={value,before:baseline};return {...old,[draftKey]:current};});}
 async function saveChanges(list:{slotId:string;value:Choice|null;before:Choice|null}[]){
  if(!poll||!memberId)throw new Error('Choose your name first.');
  const result=await operation({type:'votes',pollId:poll.id,memberId,changes:list});setDrafts(old=>({...old,[draftKey]:{}}));info('Your responses are saved. Everyone can see the latest replies.');return result;
 }
 async function save(){try{await saveChanges(Object.entries(changes).map(([slotId,x])=>({slotId,...x})));}catch{}}
 async function copy(text:string,message='Copied.'){try{await navigator.clipboard.writeText(text);info(message);}catch{setTextModal({title:'Copy this text',text});}}
 function invitation(){if(!poll||!circle)return '';return 'Subject: '+circle.title+' — '+monthLabel(poll.month)+'\n\nHi everyone,\n\nPlease add your availability for our 45-minute '+monthLabel(poll.month)+' meeting by '+dateLabel(poll.deadline,poll.timezone)+' ('+poll.timezone+').\n\n'+shared+'\n\nChoose your name, respond to the candidate times, and suggest another time if needed. Please use “Need to check” if you need to rearrange something. A Busy calendar entry does not have to rule a time out.\n\nI will confirm the final time with an Outlook invitation.\n\nThanks,\n'+circle.members.find(m=>m.id===circle.organiserId)?.name;}
 function followUp(slot?:Slot){if(!poll||!circle)return '';const a=slot?summary(slot,circle):null;const names=a?[...a.check,...a.missing].map(m=>m.name):circle.members.filter(m=>poll.slots.some(s=>!s.votes[m.id])).map(m=>m.name);return 'Hi '+(names.join(', ')||'everyone')+',\n\n'+(slot?'Could you confirm whether '+formatSlot(slot,poll.timezone)+' ('+poll.timezone+') works for our meeting? Please update your reply to Best, Available, or Unavailable once you know.':'Could you add or complete your availability for our '+monthLabel(poll.month)+' meeting?')+'\n\n'+shared+'\n\nThank you!';}
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);

 const webActions=useRef<{read:()=>unknown;save:(input:any)=>Promise<unknown>}>(null!);
 webActions.current={
  read:()=>({month:poll?.month??null,timezone:poll?.timezone??circle?.timezone,memberId:memberId||null,poll:poll??null,members:circle?.members}),
  save:async(input:any)=>{if(!memberId||!poll||!unlocked)throw new Error('Choose your name and an open poll.');if(busy||dirty)throw new Error('Finish saving or discard your unsaved page changes first.');if(!input||!Array.isArray(input.responses)||!input.responses.length||input.responses.some((x:any)=>!RESPONSES.includes(x.value)||!poll.slots.some(s=>s.id===x.slotId)))throw new Error('Invalid slot or response.');const result=await saveChanges(input.responses.map((x:any)=>({...x,before:poll.slots.find(s=>s.id===x.slotId)?.votes[memberId]??null})));return {saved:true,revision:result.revision};}
 };
 const ready=!!data;
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool||!ready)return;const lifecycle=new AbortController();
  const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'get_meeting_poll',title:'Read the current meeting poll',description:'Read the visible month, candidates, replies and selected member. Does not change the poll.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>webActions.current.read()});
  register({name:'save_my_responses',title:'Save meeting availability',description:'Save responses for the currently selected person and month. Changes the same shared replies as the Save responses button. Choose a member in the page first.',inputSchema:{type:'object',properties:{responses:{type:'array',minItems:1,items:{type:'object',properties:{slotId:{type:'string'},value:{type:'string',enum:[...RESPONSES]}},required:['slotId','value'],additionalProperties:false}}},required:['responses'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>webActions.current.save(input)});
  return()=>lifecycle.abort();
 },[ready]);

 if(!data)return <div className="site-shell"><Header/><main className="loading-page">{error?<div className="panel"><h2>We couldn’t open this circle</h2><p role="alert">{error}</p><Button onClick={()=>location.reload()}>Try again</Button><a className="text-link" href="/">Back to start</a></div>:<><p className="eyebrow">OPENING YOUR CIRCLE</p><Skeleton className="h-14 w-72"/><Skeleton className="mt-6 h-72 w-full"/></>}</main></div>;
 const c=data.circle;
 return <div className="site-shell"><Header right={<div className="header-actions">{admin&&<Button variant="ghost" className="icon-button" onClick={()=>setSettings(true)} aria-label="Circle settings"><Settings size={19}/></Button>}<span className="role-label">{admin?'Organiser':'Shared circle'}</span></div>}/><main className="workspace">
  <div className="workspace-heading"><div><p className="eyebrow">{c.title}</p><h1>{poll?monthLabel(poll.month):'Your circle is ready.'}</h1><div className="meeting-facts"><span><Users size={16}/>Five people</span><span><Clock size={16}/>45 minutes</span><span>{poll?.timezone||c.timezone}</span>{poll&&<span className={'phase '+poll.status}>{poll.status==='draft'?'Draft · only you can see this':poll.status==='open'?'Collecting replies':poll.status==='selected'?'Invitation pending':'Invitation sent'}</span>}</div></div><div className="heading-actions">{polls.length>0&&<Select value={poll?.id} onValueChange={v=>setPollId(String(v))}><SelectTrigger aria-label="Meeting month" className="picker"><SelectValue>{poll&&monthLabel(poll.month)}</SelectValue></SelectTrigger><SelectContent>{polls.map(p=><SelectItem key={p.id} value={p.id}>{monthLabel(p.month)}{p.status==='draft'?' · draft':''}</SelectItem>)}</SelectContent></Select>}{admin&&<Button className="primary-button" onClick={()=>setCreateOpen(true)}><Plus size={17}/>New month</Button>}</div></div>
  <div aria-live="polite">{notice&&<div className="notice success"><Check size={17}/>{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></div>}</div>
  {error&&<div role="alert" className="notice error"><span>{error} {dirty>0&&'Your unsaved input is still here.'}</span><Button variant="ghost" onClick={()=>refresh().then(()=>info('Latest replies loaded. Your unsaved input is preserved.')).catch(e=>setError(e.message))}>Refresh</Button></div>}
  {admin&&<div className="share-panel"><div className="share-copy"><Link2 size={20}/><div><strong>One link for the whole circle</strong><p>Send this in one email to all four supervisors.</p></div></div><div className="share-controls"><Input aria-label="Shared circle link" readOnly value={shared}/><Button variant="outline" onClick={()=>copy(shared,'Shared link copied.')}><Copy size={16}/>Copy link</Button>{poll&&poll.status!=='draft'&&<Button variant="outline" onClick={()=>setTextModal({title:'Invitation email',text:invitation()})}>Email text</Button>}</div><details><summary><LockKeyhole size={13}/>Your private management link</summary><div className="management-backup"><p>Bookmark this link to manage the circle on any device. Keep it out of group emails.</p><Input aria-label="Management link" readOnly value={manageUrl}/><Button variant="outline" onClick={()=>copy(manageUrl,'Management link copied. Keep it private.')}>Copy management link</Button></div></details></div>}
  {!poll?<Empty className="empty-panel"><EmptyHeader><div className="empty-symbol"><CalendarDays size={28}/></div><EmptyTitle>{admin?'Let’s find your first meeting time.':'No open poll yet.'}</EmptyTitle><EmptyDescription>{admin?'Create a month, add a few candidate times, and open the poll for everyone.':'The organiser will add this month’s candidate times here.'}</EmptyDescription></EmptyHeader>{admin&&<EmptyContent><Button className="primary-button" onClick={()=>setCreateOpen(true)}>Create first month <ArrowUpRight size={17}/></Button></EmptyContent>}</Empty>:
  <>
   <div className="poll-toolbar"><div><span className="muted">Reply by </span><strong>{dateLabel(poll.deadline,poll.timezone)}</strong>{poll.status==='open'&&Date.parse(poll.deadline)<Date.now()&&<span className="late-badge">Past deadline · replies still open</span>}</div><Button variant="ghost" className="refresh-button" disabled={busy} onClick={()=>refresh().then(()=>info('Latest replies loaded.')).catch(e=>setError(e.message))}><RefreshCw size={15}/>Refresh</Button></div>
   {poll.calendarUpdateNeeded&&<div className="notice caution">This poll was reopened. After choosing again, update the previous Outlook invitation.</div>}
   {(poll.status==='selected'||poll.status==='sent')&&<section className="final-panel"><div className="final-icon"><Check size={26}/></div><div><p className="eyebrow">{poll.status==='sent'?'OUTLOOK INVITATION SENT':'TIME SELECTED · OUTLOOK INVITATION PENDING'}</p><h2>{formatSlot(poll.slots.find(s=>s.id===poll.selectedId)!,poll.timezone)}</h2><p>{poll.status==='sent'?'The organiser has marked the Outlook invitation as sent.':'The time is chosen. The organiser will send or update the Outlook invitation.'}</p>{!summary(poll.slots.find(s=>s.id===poll.selectedId)!,c).allConfirmed&&<p><strong>Some attendance is unconfirmed or unavailable.</strong> See the replies below.</p>}</div>{admin&&<div className="final-actions">{poll.status==='selected'&&<><Button className="primary-button" disabled={busy} onClick={()=>operation({type:'sent',pollId:poll.id}).then(()=>info('Outlook invitation marked as sent.')).catch(()=>{})}><Send size={16}/>I’ve sent the Outlook invite</Button><Button variant="outline" onClick={()=>setTextModal({title:'Meeting details for Outlook',text:c.title+'\n'+formatSlot(poll.slots.find(s=>s.id===poll.selectedId)!,poll.timezone)+'\nTime zone: '+poll.timezone+'\nDuration: 45 minutes\nAttendees: '+c.members.map(m=>m.name).join(', ')+'\n\nUpdate this month’s occurrence in the existing Outlook series. Confirm attendance from the replies below.'})}>Copy meeting details</Button></>}<Button variant="ghost" onClick={()=>setReopen(true)}>Reopen poll</Button></div>}</section>}
   {admin&&<Tabs value={mode} onValueChange={setMode} className="mode-tabs"><TabsList><TabsTrigger value="manage">Manage meeting</TabsTrigger><TabsTrigger value="availability">My availability</TabsTrigger></TabsList></Tabs>}
   <div className="meeting-layout"><div className="main-column">
    {(!admin||mode==='availability')&&<section className="panel availability-panel"><div className="section-heading"><div><p className="eyebrow">YOUR RESPONSE</p><h2>{currentMember?'Your availability':'Choose your name to begin'}</h2></div><MemberPicker circle={c} value={memberId} onChange={selectMember} disabled={busy}/></div><p className="muted compact">Choose what really works for you, even if your calendar says Busy.</p><div className="legend">{RESPONSES.map(v=><Status key={v} value={v}/>)}</div>
     {!currentMember?<div className="choose-name"><Users size={22}/><p>Select your name above to fill in your own responses.<br/><small>Everyone can see the group’s replies below.</small></p></div>:poll.slots.length===0?<p className="muted">No candidate times yet.</p>:<div className="ballot">{poll.slots.map(s=><div className={'ballot-row '+(poll.selectedId===s.id?'chosen':'')} key={s.id}><div className="slot-label"><strong>{new Intl.DateTimeFormat('en-GB',{timeZone:poll.timezone,weekday:'short',day:'numeric',month:'short'}).format(new Date(s.start))}</strong><span>{s.time}–{localParts(new Date(Date.parse(s.start)+45*60000).toISOString(),poll.timezone).time}{Date.parse(s.start)<Date.now()?' · past':''}</span></div><RadioGroup className="vote-options" value={changes[s.id]?changes[s.id].value??'':s.votes[memberId]??''} onValueChange={v=>changeVote(s,v as Choice)} disabled={!unlocked||busy} aria-label={'Availability for '+formatSlot(s,poll.timezone)}>{RESPONSES.map(v=>{const Icon=icons[v],selected=(changes[s.id]?changes[s.id].value:s.votes[memberId])===v;return <label className={'vote-option '+v+(selected?' selected':'')} key={v}><RadioGroupItem value={v} className="vote-radio"/><Icon size={15}/><span>{LABELS[v]}</span></label>;})}</RadioGroup>{unlocked&&<Button variant="ghost" className="clear-vote" disabled={busy||!(changes[s.id]?changes[s.id].value:s.votes[memberId])} aria-label={'Clear response for '+formatSlot(s,poll.timezone)} onClick={()=>changeVote(s,null)}>Clear</Button>}</div>)}</div>}
     {currentMember&&unlocked&&<div className="save-bar"><span>{dirty?dirty+' unsaved '+(dirty===1?'change':'changes'):'Your saved replies are shared with everyone.'}</span><div>{dirty>0&&<Button variant="ghost" disabled={busy} onClick={()=>setDiscard(true)}>Discard changes</Button>}<Button className="primary-button" disabled={busy||!dirty} onClick={save}>{busy?'Saving…':'Save responses'}<Check size={16}/></Button></div></div>}
     {!unlocked&&<p className="fine">This poll is locked. The organiser can reopen it if plans change.</p>}
    </section>}
    {admin&&mode==='manage'&&unlocked&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">{poll.status==='draft'?'PREPARE THIS MONTH':'CANDIDATE TIMES'}</p><h2>{poll.status==='draft'?'Start with a few good options.':'Keep the options useful.'}</h2></div><span className="count-badge">{poll.slots.length} times</span></div><p className="muted compact">Weekdays, 09:00–17:00. Every option is 45 minutes. Start with about 6–8 times.</p><AddTimes key={poll.id} poll={poll} memberId={memberId} busy={busy} onAdd={async slots=>{await operation({type:'addSlots',pollId:poll.id,memberId,slots});info('Candidate times added. Existing replies are unchanged.');}} allowDefault/>
     <div className="candidate-list">{poll.slots.map(s=><div key={s.id}><span>{formatSlot(s,poll.timezone)}</span><Button variant="ghost" className="icon-button" aria-label={'Remove '+formatSlot(s,poll.timezone)} onClick={()=>setRemove(s)} disabled={busy}><Trash2 size={16}/></Button></div>)}</div>
     <details className="deadline-details"><summary>Edit reply deadline</summary><DeadlineForm key={poll.id+poll.deadline} poll={poll} busy={busy} onSave={async deadline=>{await operation({type:'deadline',pollId:poll.id,deadline});info('Reply deadline updated.');}}/></details>
     {poll.status==='draft'&&<div className="publish-bar"><p>Opening the poll makes these times visible through your shared link.</p><Button className="primary-button" disabled={busy||!poll.slots.length} onClick={()=>operation({type:'publish',pollId:poll.id}).then(()=>info('Poll opened. Copy the invitation email to share it.')).catch(()=>{})}>Open poll <ArrowUpRight size={17}/></Button></div>}
    </section>}
    <section className="panel overview-panel"><div className="section-heading"><div><p className="eyebrow">THE WHOLE CIRCLE</p><h2>Everyone’s availability</h2></div><span className="count-badge">{c.members.filter(m=>poll.slots.length>0&&poll.slots.every(s=>s.votes[m.id])).length}/5 complete</span></div>
    <div className="member-progress">{c.members.map((m,i)=>{const answered=poll.slots.filter(s=>s.votes[m.id]).length;const status=answered===0?'Not started':answered===poll.slots.length?'Complete':'Needs update';return <div key={m.id}><span className={'avatar avatar-'+i}>{initials(m.name)}</span><span><strong>{m.name}</strong><small className={status==='Complete'?'complete':''}>{status}</small></span></div>;})}</div>
    {poll.slots.length>0?<Table className="overview-table"><TableHeader><TableRow><TableHead>Candidate time</TableHead>{c.members.map(m=><TableHead key={m.id}>{m.name}</TableHead>)}</TableRow></TableHeader><TableBody>{poll.slots.map(s=><TableRow key={s.id} className={s.id===poll.selectedId?'selected-row':''}><TableCell><strong>{formatSlot(s,poll.timezone)}</strong>{s.id===poll.selectedId&&<span className="selected-tag">Selected</span>}</TableCell>{c.members.map(m=><TableCell key={m.id}><Status value={s.votes[m.id]}/></TableCell>)}</TableRow>)}</TableBody></Table>:<p className="muted">Replies will appear here once candidate times are added.</p>}</section>
    {(!admin||mode==='availability')&&unlocked&&<section className="panel suggestion-panel"><div><p className="eyebrow">ANOTHER TIME IN MIND?</p><h2>Suggest a time</h2><p className="muted compact">Add another option for everyone to consider. Then add your response above.</p></div><AddTimes key={poll.id} poll={poll} memberId={memberId} busy={busy} onAdd={async slots=>{if(!memberId)throw new Error('Choose your name first.');await operation({type:'addSlots',pollId:poll.id,memberId,slots});info('Time added. Please mark your availability for the new option.');}}/></section>}
   </div><aside className="recommendations"><section className="panel recommendation-panel"><p className="eyebrow">FINDING THE FIT</p><h2>{candidates.some(s=>summary(s,c).allConfirmed)?'Good times, together.':'A little coordination.'}</h2><p className="muted compact">Five clear yeses come first. “Need to check” is never counted as confirmed.</p>{candidates.length===0?<p className="fine">Recommendations appear as your circle responds.</p>:['confirmed','coordination','absence'].map(group=>{const list=candidates.filter(s=>{const a=summary(s,c);return group==='confirmed'?a.allConfirmed:group==='absence'?a.unavailable.length>0:!a.allConfirmed&&!a.unavailable.length;});if(!list.length)return null;return <div className="recommendation-group" key={group}><h3>{group==='confirmed'?'Everyone can attend':group==='coordination'?'Needs coordination':'Alternatives with absences'}</h3>{list.map(s=>{const a=summary(s,c);return <article className={'recommendation '+group} key={s.id}><strong>{formatSlot(s,poll.timezone)}</strong><div className="five-dots" aria-label={a.confirmed+' confirmed out of five'}>{c.members.map(m=><span key={m.id} className={s.votes[m.id]||'none'} title={m.name+': '+(LABELS[s.votes[m.id]]||'No response')}/>)}</div><p>{a.confirmed} confirmed{a.best.length?' · '+a.best.length+' best':''}{a.check.length?' · '+a.check.length+' to check':''}{a.missing.length?' · '+a.missing.length+' no response':''}{a.unavailable.length?' · '+a.unavailable.length+' unavailable':''}</p>{a.check.length>0&&<small>To check: {a.check.map(m=>m.name).join(', ')}</small>}{a.missing.length>0&&<small>No response: {a.missing.map(m=>m.name).join(', ')}</small>}{a.unavailable.length>0&&<small>Unavailable: {a.unavailable.map(m=>m.name).join(', ')}</small>}{admin&&poll.status==='open'&&<div className="recommendation-actions"><Button variant={a.allConfirmed?'default':'outline'} disabled={busy||!a.organiserReady||Date.parse(s.start)<Date.now()} onClick={()=>setDecision({slot:s,revision:data.revision})}>{a.allConfirmed?'Choose this time':'Review this option'}</Button>{(a.check.length>0||a.missing.length>0)&&<Button variant="ghost" onClick={()=>setTextModal({title:'Confirmation request',text:followUp(s)})}>Follow up</Button>}{!a.organiserReady&&<small>Add your own availability before choosing.</small>}</div>}</article>;})}</div>;})}</section>{admin&&poll.status==='open'&&<Button variant="outline" className="follow-up-button" onClick={()=>setTextModal({title:'Follow-up email',text:followUp()})}><Copy size={16}/>Copy a reminder</Button>}</aside></div>
  </>}
 </main><footer className="app-footer"><span>Shared by your circle. Updated as replies arrive.</span><span>Choosing a name is a convenience, not a sign-in.</span></footer>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Circle settings</DialogTitle><DialogDescription>Names keep their existing replies. Time zone changes apply to new months.</DialogDescription></DialogHeader><SettingsForm circle={c} busy={busy} onSave={async x=>{await operation({type:'settings',...x});setSettings(false);info('Circle settings saved.');}}/></DialogContent></Dialog>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>A fresh month, same circle.</DialogTitle><DialogDescription>Last month’s replies won’t be carried forward.</DialogDescription></DialogHeader><CreatePollForm circle={c} busy={busy} onCreate={async x=>{const result=await operation({type:'createPoll',...x});setPollId(result.circle.polls.find(p=>p.month===x.month)!.id);setMode('manage');setCreateOpen(false);info('Draft created. Add your candidate times.');}}/></DialogContent></Dialog>
 <Dialog open={!!textModal} onOpenChange={v=>!v&&setTextModal(null)}><DialogContent className="text-dialog"><DialogHeader><DialogTitle>{textModal?.title}</DialogTitle><DialogDescription>Copy this into Outlook. Nothing is sent automatically.</DialogDescription></DialogHeader><textarea aria-label={textModal?.title||'Message text'} readOnly value={textModal?.text||''} rows={14}/><Button className="primary-button" onClick={()=>copy(textModal?.text||'','Text copied. Ready to paste into Outlook.')}><Copy size={16}/>Copy text</Button></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={v=>!v&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this candidate?</AlertDialogTitle><AlertDialogDescription>{remove&&poll&&formatSlot(remove,poll.timezone)}. Its replies will be removed. To change a time, add a new candidate and collect new replies.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep time</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>operation({type:'removeSlot',pollId:poll?.id,slotId:remove?.id}).then(()=>{setRemove(null);info('Candidate removed.');}).catch(()=>{})}>Remove time</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!decision} onOpenChange={v=>!v&&setDecision(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Choose this meeting time?</AlertDialogTitle><AlertDialogDescription>{decision&&poll&&formatSlot(decision.slot,poll.timezone)}. This locks the poll. You will still need to send or update the Outlook invitation.</AlertDialogDescription></AlertDialogHeader>{decision&&<div className="decision-replies">{c.members.map(m=><div key={m.id}><span>{m.name}</span><Status value={decision.slot.votes[m.id]}/></div>)}{!summary(decision.slot,c).allConfirmed&&<p className="notice caution">This is not a fully confirmed meeting. Choosing it accepts the absences and unconfirmed replies listed here.</p>}</div>}<AlertDialogFooter><AlertDialogCancel>Keep coordinating</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{const d=decision;setDecision(null);operation({type:'finalize',pollId:poll?.id,slotId:d?.slot.id,expectedRevision:d?.revision,acceptIncomplete:true}).then(()=>info('Time selected. Now update the Outlook invitation.')).catch(()=>{});}}>Choose time</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={reopen} onOpenChange={setReopen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reopen this poll?</AlertDialogTitle><AlertDialogDescription>Existing replies stay in place. People can edit them again. If you have already sent an Outlook invitation, update it after choosing a new time.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep selected time</AlertDialogCancel><AlertDialogAction onClick={()=>operation({type:'reopen',pollId:poll?.id}).then(()=>{setReopen(false);info('Poll reopened.');}).catch(()=>{})}>Reopen poll</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard your unsaved changes?</AlertDialogTitle><AlertDialogDescription>Your last saved replies stay in the shared poll. Your local changes for this person and month will be cleared.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={()=>{setDrafts(old=>({...old,[draftKey]:{}}));setDiscard(false);refresh().catch(()=>{});info('Unsaved changes discarded.');}}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}

export function Header({right}:{right?:React.ReactNode}){return <header className="topbar"><a className="brand" href="/"><span className="brand-mark"><CalendarDays size={22}/></span>Supervision Circle</a>{right||<span className="topnote">A little less back-and-forth.</span>}</header>;}
function AddTimes({poll,memberId,busy,onAdd,allowDefault=false}:{poll:Poll;memberId:string;busy:boolean;onAdd:(slots:{date:string;time:string}[])=>Promise<void>;allowDefault?:boolean}){
 const [date,setDate]=useState(poll.month+'-01'),[time,setTime]=useState('10:00'),[error,setError]=useState('');
 async function add(d=date,t=time){setError('');try{await onAdd([{date:d,time:t}]);}catch(e){setError(e instanceof Error?e.message:'Could not add time.');}}
 const last=new Date(Number(poll.month.slice(0,4)),Number(poll.month.slice(5)),0).getDate();
 return <div className="add-times"><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void add(String(form.get('date')),String(form.get('time')));}}><label>Date<Input aria-label="Candidate date" name="date" type="date" value={date} min={poll.month+'-01'} max={poll.month+'-'+last} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)} required/></label><label>Starts<Input aria-label="Candidate start time" name="time" type="time" value={time} min="09:00" max="16:15" step={900} onInput={e=>setTime(e.currentTarget.value)} onChange={e=>setTime(e.target.value)} required/></label><Button className="primary-button" type="submit" disabled={busy||(!allowDefault&&!memberId)}><Plus size={16}/>Add time</Button></form>{allowDefault&&<Button variant="ghost" className="default-time" disabled={busy} onClick={()=>{const first=new Date(poll.month+'-01T12:00:00Z');const day=1+(2-first.getUTCDay()+7)%7+14;void add(poll.month+'-'+String(day).padStart(2,'0'),'16:00');}}>Add third Tuesday · 16:00–16:45</Button>}{error&&<p role="alert" className="field-error">{error}</p>}</div>;
}
function CreatePollForm({circle,busy,onCreate}:{circle:Circle;busy:boolean;onCreate:(x:{month:string;deadline:string})=>Promise<void>}){const [month,setMonth]=useState(nextMonth(circle.timezone)),[deadline,setDeadline]=useState(defaultDeadline(circle.timezone)),[error,setError]=useState('');return <form className="stack-form" onSubmit={async e=>{e.preventDefault();try{await onCreate({month,deadline});}catch(e){setError((e as Error).message);}}}><label>Meeting month<Input type="month" value={month} onInput={e=>setMonth(e.currentTarget.value)} onChange={e=>setMonth(e.target.value)} required/></label><label>Reply deadline · {circle.timezone}<Input type="datetime-local" value={deadline} onInput={e=>setDeadline(e.currentTarget.value)} onChange={e=>setDeadline(e.target.value)} required/></label><p className="fine">The deadline is a reminder. Replies stay open until you choose the meeting time.</p>{error&&<p className="field-error" role="alert">{error}</p>}<Button type="submit" className="primary-button" disabled={busy}>Create draft <ArrowUpRight size={16}/></Button></form>;}
function DeadlineForm({poll,busy,onSave}:{poll:Poll;busy:boolean;onSave:(value:string)=>Promise<void>}){const p=localParts(poll.deadline,poll.timezone);const [value,setValue]=useState(p.date+'T'+p.time),[error,setError]=useState('');return <form className="inline-form" onSubmit={async e=>{e.preventDefault();try{await onSave(value);}catch(e){setError((e as Error).message);}}}><label>Reply by · {poll.timezone}<Input type="datetime-local" required value={value} onInput={e=>setValue(e.currentTarget.value)} onChange={e=>setValue(e.target.value)}/></label><Button type="submit" variant="outline" disabled={busy}>Save deadline</Button>{error&&<p className="field-error">{error}</p>}</form>;}
export function SettingsForm({circle,busy,onSave}:{circle:Circle;busy:boolean;onSave:(x:{title:string;names:string[];timezone:string})=>Promise<void>}){const [title,setTitle]=useState(circle.title),[names,setNames]=useState(circle.members.map(m=>m.name)),[timezone,setTimezone]=useState(circle.timezone),[error,setError]=useState('');return <form className="stack-form" onSubmit={async e=>{e.preventDefault();setError('');try{await onSave({title,names,timezone});}catch(e){setError((e as Error).message);}}}><label>Meeting name<Input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={100}/></label><div className="name-fields">{names.map((n,i)=><label key={i}>{i===0?'Your name · organiser':'Supervisor '+i}<Input value={n} onChange={e=>setNames(names.map((v,j)=>i===j?e.target.value:v))} placeholder={i===0?'Your name':'Full name'} required maxLength={60}/></label>)}</div><label>Time zone<Input value={timezone} onChange={e=>setTimezone(e.target.value)} placeholder="Europe/London" required/></label>{error&&<p role="alert" className="field-error">{error}</p>}<Button type="submit" className="primary-button" disabled={busy}>{busy?'Saving…':'Save circle'}<ArrowUpRight size={16}/></Button></form>;}


